name: Linting Generated Blueprints Advanced

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  framework_matrix:
    strategy:
      matrix:
        framework: [chi, gin, fiber, gorilla/mux, httprouter, standard-library, echo]
        driver: [postgres]
        git: [commit]
        advanced: [htmx, githubaction, websocket, tailwind, docker, react]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.63.4

      - name: Commit report
        run: |
          git config --global user.name 'testname'
          git config --global user.email 'testemail@users.noreply.github.com'

      - name: Set framework variable
        id: set-proejct-directory
        run: echo "PROJECT_DIRECTORY=${{ matrix.framework }}" | sed 's/\//-/g' >> $GITHUB_ENV

      - name: build templates
        run: script -q /dev/null -c "go run main.go create -n ${{ env.PROJECT_DIRECTORY }} -f ${{ matrix.framework}} -d ${{ matrix.driver }} -g ${{ matrix.git}} --advanced --feature ${{ matrix.advanced }}"

      - if: ${{ matrix.advanced == 'htmx' || matrix.advanced == 'tailwind' }}
        name: Install Templ & gen templates
        run: | 
          go install github.com/a-h/templ/cmd/templ@latest
          /home/runner/go/bin/templ generate -path ${{ env.PROJECT_DIRECTORY }}

      - name: golangci-lint
        run: | 
          cd ${{ env.PROJECT_DIRECTORY }}
          golangci-lint run

      - name: remove templates
        run: rm -rf ${{ env.PROJECT_DIRECTORY }}
